<a href="https://colab.research.google.com/github/hudanurengin/M.A.R.S-teknoloji-gorev/blob/main/Feed_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch

In [16]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
x=torch.flatten(x)
x

tensor([1., 2., 3., 4., 5., 6.])

In [17]:
torch.manual_seed(1)


input_size = 6
hidden_size = 50

hidden_weight= torch.randn(input_size, hidden_size)
hidden_bias = torch.randn(hidden_size)


In [18]:
output_size = 1

output_weight = torch.randn(hidden_size, output_size)
output_bias = torch.randn(output_size)



In [19]:
def sigmoid_activation(x):

  return 1 / (1 + torch.exp(-x))

In [20]:
def tanh_activation(x):

    return (torch.exp(x) - torch.exp(-x))/(torch.exp(x) + torch.exp(-x))

In [21]:
#hidden layer
hidden_layer = torch.matmul(x, hidden_weight) + hidden_bias
hidden_activation= tanh_activation(hidden_layer)
hidden_activation2= torch.tanh(hidden_layer)

# Output layer
output_layer= torch.matmul(hidden_activation, output_weight) + output_bias
output_activation= sigmoid_activation(output_layer)
output_activation2= torch.sigmoid(output_layer)

output_activation,output_activation2

(tensor([0.0575]), tensor([0.0575]))

Okul numaramı seed e verdiğim hali

In [26]:
torch.manual_seed(180401051)

input_size = 6
hidden_size = 50

hidden_weight= torch.randn(input_size, hidden_size)
hidden_bias = torch.randn(hidden_size)

output_size = 1

output_weight = torch.randn(hidden_size, output_size)
output_bias = torch.randn(output_size)

def sigmoid_activation(x):

  return 1 / (1 + torch.exp(-x))

def tanh_activation(x):

    return (torch.exp(x) - torch.exp(-x))/(torch.exp(x) + torch.exp(-x))

#hidden layer
hidden_layer = torch.matmul(x, hidden_weight) + hidden_bias
hidden_activation= tanh_activation(hidden_layer)
hidden_activation2= torch.tanh(hidden_layer)

# Output layer
output_layer= torch.matmul(hidden_activation, output_weight) + output_bias
output_activation= sigmoid_activation(output_layer)
output_activation2= torch.sigmoid(output_layer)

output_activation,output_activation2

(tensor([1.0000]), tensor([1.0000]))